name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Publish
      working-directory: ./src
      run: dotnet publish --no-build -c Release -o ./publish-output
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UserAPI
        path: ./src/publish-output/
        if-no-files-found: error
    - name: Zip Artifact
      working-directory: ./src
      run: zip -r UserAPI.zip ./publish-output/
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: UserAPI.zip
